#!/usr/bin/env python
import sys
from math import log

REVISION = 1

def main(argv):
    sys.stderr.write("Assign logProb to set of training labels: Copyright 2013 Ed Grefenstette, %d" % REVISION)
    trainingLabelPath = argv[1]
    labelCounts = {}
    total = 0
    for line in open(trainingLabelPath):
        label = line.strip()
        labelCounts[label] = labelCounts.get(label,0) + 1
        total += 1

    logTotal = log(total)

    for label in labelCounts:
        logLabelCount = log(labelCounts[label])
        print label, logLabelCount - logTotal

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print "Syntax:", sys.argv[0], "trainingLabels"
        sys.exit()
    main(sys.argv)